'use client';
import { useEffect, useState } from 'react';
import { defaultMapping, examples, initialStore, processOrder, type Mapping, type Order, type Store } from './engine';
const key = 'herin-order-demo-v1';
const json = (o: unknown) => JSON.stringify(o, null, 2);
export default function Demo() {
  const [orderText, setOrderText] = useState(json(examples[1].order));
  const [mappingText, setMappingText] = useState(json(defaultMapping));
  const [store, setStore] = useState<Store>(initialStore);
  const [message, setMessage] = useState('Choose an example or edit the sample payload, then run it.');
  const [timeZone, setTimeZone] = useState('America/Los_Angeles');
  useEffect(() => { try { const saved = localStorage.getItem(key); if (saved) { const s = JSON.parse(saved); if (Array.isArray(s?.fulfillment) && Array.isArray(s?.payments)) setStore(s); } } catch { /* ignore damaged demo data */ } }, []);
  function run() {
    try {
      const mapping = JSON.parse(mappingText) as Mapping[];
      const order = JSON.parse(orderText) as Order;
      if (!Array.isArray(mapping)) throw Error('Mapping must be an array.');
      const next = processOrder(order, mapping, store, timeZone);
      setStore(next.store);
      localStorage.setItem(key, json(next.store));
      setMessage(next.status === 'duplicate' ? `Duplicate ${next.result.orderId}: skipped both destination writes.` : `Processed ${next.result.lineCount} line items. Added 1 fulfillment row and 1 payments row${next.result.unmapped.length ? `; ${next.result.unmapped.length} unmapped title(s) flagged.` : '.'}`);
    } catch (e) { setMessage(`Could not process: ${e instanceof Error ? e.message : 'invalid payload'}`); }
  }
  return <main className="min-h-screen bg-[#f4f4f0] text-[#20251f] px-4 py-8 md:px-10 font-sans">
    <div className="mx-auto max-w-7xl">
      <a href="/#demos" className="text-sm text-emerald-800 underline">← Back to herin.id demos</a>
      <div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="uppercase text-xs tracking-[.2em] font-semibold text-emerald-800">Interactive workflow demo · Sample data</p><h1 className="text-3xl md:text-5xl font-semibold tracking-tight mt-2">Multi-item order automation</h1><p className="mt-3 max-w-2xl text-slate-600">Try a Shopify-shaped order payload. Each item is looked up independently, then combined into one fulfillment row and one payment row. Unknown titles are flagged, not dropped.</p></div><span className="rounded-full bg-amber-100 text-amber-900 px-4 py-2 text-sm">Simulation · no live integrations</span></div>
      <div className="bg-white border border-slate-200 rounded-2xl p-4 mt-7 text-sm text-slate-700"><b>What is real here:</b> editable input, actual transformation code, duplicate checks, and browser-local outputs. <b>What is not connected:</b> Shopify webhooks, a Zapier account, or Google Sheets. All order data below is synthetic. Each visitor has a separate browser-local workspace; no real orders or client data are read or changed.</div>
      <div className="mt-7 grid lg:grid-cols-2 gap-5"><section className="rounded-2xl bg-white border border-slate-200 p-5"><h2 className="text-xl font-semibold">1. Order payload</h2><div className="flex gap-2 flex-wrap my-4">{examples.map((ex, i) => <button key={ex.label} onClick={() => setOrderText(json(ex.order))} className="rounded-full border border-slate-300 hover:bg-emerald-50 px-3 py-1.5 text-sm">{i + 1}. {ex.label}</button>)}</div><label htmlFor="payload" className="text-sm font-medium">Edit the Shopify-shaped JSON</label><textarea id="payload" spellCheck={false} value={orderText} onChange={e => setOrderText(e.target.value)} className="block mt-2 w-full h-64 rounded-xl border border-slate-300 bg-slate-950 text-emerald-200 p-4 font-mono text-xs md:text-sm" /></section>
      <section className="rounded-2xl bg-white border border-slate-200 p-5"><h2 className="text-xl font-semibold">2. SKU lookup table</h2><p className="mt-2 mb-4 text-sm text-slate-600">Edit this map and rerun a new order. Exact title matching ignores case and surrounding whitespace.</p><label htmlFor="mapping" className="text-sm font-medium">Sample mapping</label><textarea id="mapping" spellCheck={false} value={mappingText} onChange={e => setMappingText(e.target.value)} className="block mt-2 w-full h-64 rounded-xl border border-slate-300 bg-slate-950 text-emerald-200 p-4 font-mono text-xs md:text-sm" /><label className="block mt-4 text-sm font-medium" htmlFor="timezone">Reporting timezone</label><select id="timezone" value={timeZone} onChange={e => setTimeZone(e.target.value)} className="mt-2 rounded-lg border border-slate-300 p-2"><option value="America/Los_Angeles">America/Los_Angeles</option><option value="Asia/Jakarta">Asia/Jakarta</option><option value="UTC">UTC</option></select></section></div>
      <div className="mt-5 flex flex-wrap gap-3 items-center"><button onClick={run} className="rounded-xl bg-emerald-800 text-white px-6 py-3 font-semibold hover:bg-emerald-700">Run workflow →</button><button onClick={() => { setStore(initialStore); localStorage.removeItem(key); setMessage('Cleared browser-local rows.'); }} className="rounded-xl border border-slate-300 px-5 py-3">Clear demo rows</button><p role="status" className="text-sm text-slate-700">{message}</p></div>
      <div className="mt-8 grid xl:grid-cols-2 gap-5"><section className="rounded-2xl bg-white border border-slate-200 p-5 overflow-x-auto"><h2 className="text-xl font-semibold">3. Fulfillment output <span className="text-sm text-slate-500">({store.fulfillment.length} rows)</span></h2><p className="text-sm text-slate-600 mt-1">One row per order, line breaks preserved inside cells.</p><table className="w-full text-left text-sm mt-4 border-collapse"><thead><tr>{['Order ID','Date','Products','SKU result'].map(h => <th className="p-2 border-b" key={h}>{h}</th>)}</tr></thead><tbody>{store.fulfillment.map(r => <tr key={r.orderId}><td className="p-2 border-b align-top font-mono">{r.orderId}</td><td className="p-2 border-b align-top whitespace-nowrap">{r.date}</td><td className="p-2 border-b align-top whitespace-pre-line min-w-40">{r.products}</td><td className="p-2 border-b align-top whitespace-pre-line min-w-44">{r.skus}</td></tr>)}</tbody></table>{!store.fulfillment.length && <p className="text-slate-500 my-6">No output yet.</p>}</section><section className="rounded-2xl bg-white border border-slate-200 p-5 overflow-x-auto"><h2 className="text-xl font-semibold">4. Payments output <span className="text-sm text-slate-500">({store.payments.length} rows)</span></h2><p className="text-sm text-slate-600 mt-1">Same order ID. Replays do not append duplicates.</p><table className="w-full text-left text-sm mt-4"><thead><tr>{['Order ID','Date','Total (demo USD)'].map(h => <th key={h} className="p-2 border-b">{h}</th>)}</tr></thead><tbody>{store.payments.map(r => <tr key={r.orderId}><td className="p-2 border-b font-mono">{r.orderId}</td><td className="p-2 border-b">{r.date}</td><td className="p-2 border-b">${r.total.toFixed(2)}</td></tr>)}</tbody></table>{!store.payments.length && <p className="text-slate-500 my-6">No output yet.</p>}</section></div>
      <p className="text-xs text-slate-500 mt-7">Designed to demonstrate the per-item lookup and output logic. A production Zap still needs real credentials, webhook validation, retries, race-safe idempotency storage, and field mapping against the client&apos;s actual sheets.</p>
    </div>
  </main>;
}
